---
# Azure
azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
azure_resource_group: "honeypot-rg"
azure_location: "swedencentral"
azure_vm_size: "Standard_B1ms"
azure_vm_image: "Canonical:ubuntu-24_04-lts:server:latest"

# Azure Monitor / Sentinel
log_analytics_workspace_id: "{{ lookup('env', 'LOG_ANALYTICS_WORKSPACE_ID') }}"
log_analytics_workspace_key: "{{ lookup('env', 'LOG_ANALYTICS_WORKSPACE_KEY') }}"

# Sallitut inbound-portit
honeypot_open_ports:
  - { port: 22,   proto: "Tcp",  name: "SSH" }
  - { port: 23,   proto: "Tcp",  name: "Telnet" }
  - { port: 80,   proto: "Tcp",  name: "HTTP" }
  - { port: 443,  proto: "Tcp",  name: "HTTPS" }
  - { port: 445,  proto: "Tcp",  name: "SMB" }
  - { port: 3306, proto: "Tcp",  name: "MySQL" }
  - { port: 5900, proto: "Tcp",  name: "VNC" }