- name: Check if psql is initialized
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgdata

- name: Initialize psql database
  command: /usr/bin/postgresql-setup --initdb
  when: not pgdata.stat.exists
  notify: Restart psql

- name: start psql
  service:
    name: postgresql
    state: started
    enabled: true

- name: create honeypot database
  community.postgresql.postgresql_db:
    name: sales
    state: present
  become: true
  become_user: postgres

- name: create psqladmin user
  community.postgresql.postgresql_user:
    name: psqladmin
    password:  "{{ psqladmin_password }}"
    db: sales
    state: present
    role_attr_flags: SUPERUSER
  become: true
  become_user: postgres


- name: create psqluser user
  community.postgresql.postgresql_user:
    name: psqluser
    password:  "{{ psqluser_password }}"
    db: sales
    state: present
  become: true
  become_user: postgres

- name: Give access to sales database for psqluser
  community.postgresql.postgresql_privs:
    db: sales
    role: psqluser
    type: database
    privs: CONNECT
  become: true
  become_user: postgres

- name: Create table customers in sales database
  community.postgresql.postgresql_query:
    db: sales
    query: "CREATE TABLE IF NOT EXISTS customers (id SERIAL PRIMARY KEY, name VARCHAR(255), email VARCHAR(255));"
  become: true
  become_user: postgres

- name: Create table products in sales database
  community.postgresql.postgresql_query:
    db: sales
    query: "CREATE TABLE IF NOT EXISTS products (id SERIAL PRIMARY KEY, name VARCHAR(255), price DECIMAL);"
  become: true
  become_user: postgres

- name: Create table orders in sales database
  community.postgresql.postgresql_query:
    db: sales
    query: "CREATE TABLE IF NOT EXISTS orders (id SERIAL PRIMARY KEY, customer_id INTEGER REFERENCES customers(id), product_id INTEGER REFERENCES products(id), amount INTEGER, order_date DATE);"
  become: true
  become_user: postgres


  # ------------ DATA CREATION -------------- #

- name: Check if data exists in customers table
  community.postgresql.postgresql_query:
    db: sales
    query: "SELECT COUNT(*) FROM customers;"
  register: customer_count
  become: true
  become_user: postgres

- name: Insert fake data into customers table
  community.postgresql.postgresql_query:
    db: sales
    query: "INSERT INTO customers (name, email) VALUES ('Jaakko Orres', 'jakio@bleepers.com'), ('Kristian Kuusela', 'krisse@madsecurity.com'), ('Flag Flagerson', 'flag@4792048592334.com');"
  become: true
  become_user: postgres
  when: customer_count.query_result[0].count |int == 0

- name: Check if data exists in products table
  community.postgresql.postgresql_query:
    db: sales
    query: "SELECT COUNT(*) FROM products;"
  register: product_count
  become: true
  become_user: postgres

- name: Insert fake data into products table
  community.postgresql.postgresql_query:
    db: sales
    query: "INSERT INTO products (name, price) VALUES ('Laptop', 999.99), ('Mouse', 29.99), ('Keyboard', 79.99);"
  become: true
  become_user: postgres
  when: product_count.query_result[0].count |int == 0

- name: Check if data exists in orders table
  community.postgresql.postgresql_query:
    db: sales
    query: "SELECT COUNT(*) FROM orders;"
  register: order_count
  become: true
  become_user: postgres

- name: Insert fake data into orders table
  community.postgresql.postgresql_query:
    db: sales
    query: "INSERT INTO orders (customer_id, product_id, amount, order_date) VALUES (1, 1, 1, '2024-01-01'), (2, 2, 2, '2024-01-02'), (3, 3, 1, '2024-01-03');"
  become: true
  become_user: postgres
  when: order_count.query_result[0].count |int == 0