- name: Check if psql is initialized
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgdata

- name: Initialize psql database
  command: /usr/bin/postgresql-setup --initdb
  when: not pgdata.stat.exists
  notify: Restart psql

- name: start psql
  service:
    name: postgresql
    state: started
    enabled: true

- name: create honeypot database
  community.postgresql.postgresql_db:
    name: sales
    state: present
  become: true
  become_user: postgres

- name: create psqladmin user
  community.postgresql.postgresql_user:
    name: psqladmin
    password:  "{{ psqladmin_password }}"
    db: sales
    state: present
    role_attr_flags: SUPERUSER
  become: true
  become_user: postgres


- name: create psqluser user
  community.postgresql.postgresql_user:
    name: psqluser
    password:  "{{ psqluser_password }}"
    db: sales
    state: present
  become: true
  become_user: postgres

- name: Give access to sales database for psqluser
  community.postgresql.postgresql_privs:
    db: sales
    role: psqluser
    type: database
    privs: CONNECT
  become: true
  become_user: postgres