---
- name: Restart SSH
  service:
    name: sshd   # RHEL: sshd, Ubuntu: ssh
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Restart auditd
  service:
    name: auditd
    state: restarted

- name: Reload firewalld
  command: firewall-cmd --reload
