---
## inventory/group_vars/all.yml
## GITIGNORED – ei mene repoon.

# ─── Honeypot-identiteetti ────────────────────────────────────────────────────
lure_hostname: "pava-p-db01"

# ─── Azure-infrastruktuuri ────────────────────────────────────────────────────
azure_subscription_id: "4d4bbf58-87e9-44cd-a3ec-d9bc4e0d7304"
azure_resource_group:  "RG-TEST"
azure_location:        "swedencentral"
azure_vm_size:         "Standard_B1ms"
azure_vm_image:        "Canonical:ubuntu-24_04-lts:server:latest"

# ─── Azure Monitor / Sentinel ─────────────────────────────────────────────────
log_analytics_workspace_id:  ""
log_analytics_workspace_key: ""

# ─── Honeypot-portit ──────────────────────────────────────────────────────────
honeypot_open_ports:
  - { port: 22,   proto: "tcp", name: "SSH" }
  - { port: 23,   proto: "tcp", name: "Telnet" }
  - { port: 80,   proto: "tcp", name: "HTTP" }
  - { port: 443,  proto: "tcp", name: "HTTPS" }
  - { port: 445,  proto: "tcp", name: "SMB" }
  - { port: 3306, proto: "tcp", name: "MySQL" }
  - { port: 5900, proto: "tcp", name: "VNC" }

# ─── PSQL ──────────────────────────────────────────────────────────
psqladmin_password: "password123"
psqluser_password: "password456"



#-----WireGuard------------------
wireguard_port: 51820
wireguard_network: "10.100.100.0/24"

wireguard_server_address: "10.100.100.1/24"
wireguard_admin1_address: "10.100.100.2/24"
wireguard_admin2_address: "10.100.100.3/24"


